# Generated by Django 2.0.5 on 2018-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('workclass', models.CharField(max_length=20)),
                ('fnlwgt', models.IntegerField()),
                ('education', models.CharField(max_length=40)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=40)),
                ('relationship', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=20)),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=50)),
            ],
        ),
    ]
