# Generated by Django 2.0.5 on 2018-07-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0002_remove_adult_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='makes',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
