# Generated by Django 2.0.5 on 2018-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0003_adult_makes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='makes',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
