# Generated by Django 2.0.5 on 2018-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adults', '0005_adult_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='marital_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adult',
            name='race',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adult',
            name='relationship',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adult',
            name='sex',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adult',
            name='workclass',
            field=models.CharField(max_length=40),
        ),
    ]
